const LOGIN_USER = "LOGIN_USER";
const FLUSH_USER = "FLUSH_USER";
const IS_LOADING = "IS_LOADING";
const SET_USER = "SET_USER";
const SET_LOADING = "SET_LOADING";
const SET_SOCKET = "SET_SOCKET"
const SET_MODAL = "SET_MODAL";
const SET_SEARCHED_USER = "SET_SEARCHED_USER";

export { LOGIN_USER, FLUSH_USER, IS_LOADING, SET_USER, SET_LOADING, SET_SOCKET, SET_MODAL };